/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ANOTACAO (
    I_COD_ANOTACAO  BIGINT NOT NULL,
    I_COD_TAREFA    BIGINT,
    I_COD_USUARIO   BIGINT,
    S_ANOTACAO      INTEGER
);

CREATE TABLE DOCUMENTOS (
    I_COD_DOCUMENTO  BIGINT NOT NULL,
    I_COD_TAREFA     BIGINT,
    S_DOCUMENTO      VARCHAR(255)
);

CREATE TABLE EVENTO (
    I_COD_EVENTO  BIGINT NOT NULL,
    I_COD_TAREFA  BIGINT NOT NULL,
    I_COD_TIPO    BIGINT,
    DT_INI        TIMESTAMP,
    DT_FIN        TIMESTAMP,
    HR_TEMPO      TIME,
    S_OBS_PARADA  VARCHAR(100)
);

CREATE TABLE PRIORIDADES (
    I_COD_PRIORIDADE  BIGINT NOT NULL,
    S_NOME            VARCHAR(50)
);

CREATE TABLE R_USUARIO (
    I_COD_R_USUARIO  BIGINT NOT NULL,
    I_COD_USUARIO    BIGINT,
    I_COD_TAREFA     BIGINT
);

CREATE TABLE SITUACAO (
    I_COD_SITUACAO  BIGINT NOT NULL,
    S_NOME          VARCHAR(50)
);

CREATE TABLE TAREFAS (
    I_COD_TAREFA      BIGINT NOT NULL,
    I_COD_VERSAO      BIGINT,
    I_COD_SITUACAO    BIGINT NOT NULL,
    I_COD_PRIORIDADE  BIGINT,
    S_NOME            VARCHAR(255),
    S_DESCRICAO       VARCHAR(255),
    DT_INI            DATE,
    I_ESTIMATIVA      INTEGER,
    I_REALIZADO       INTEGER,
    I_PERC_CONCLUSAO  INTEGER
);

CREATE TABLE TIPO (
    I_COD_TIPO  BIGINT NOT NULL,
    S_NOME      VARCHAR(50)
);

CREATE TABLE USUARIOS (
    I_COD_USUARIO  BIGINT NOT NULL,
    S_NOME         VARCHAR(50),
    S_USUARIO      VARCHAR(10),
    S_SENHA        VARCHAR(10)
);

CREATE TABLE VERSAO (
    I_COD_VERSAO  BIGINT NOT NULL,
    S_NOME        VARCHAR(100)
);


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ANOTACAO ADD CONSTRAINT PK_ANOTACAO PRIMARY KEY (I_COD_ANOTACAO);
ALTER TABLE DOCUMENTOS ADD CONSTRAINT PK_DOCUMENTOS PRIMARY KEY (I_COD_DOCUMENTO);
ALTER TABLE EVENTO ADD CONSTRAINT PK_EVENTO PRIMARY KEY (I_COD_EVENTO);
ALTER TABLE PRIORIDADES ADD CONSTRAINT PK_PRIORIDADES PRIMARY KEY (I_COD_PRIORIDADE);
ALTER TABLE R_USUARIO ADD CONSTRAINT PK_R_USUARIO PRIMARY KEY (I_COD_R_USUARIO);
ALTER TABLE SITUACAO ADD CONSTRAINT PK_SITUACAO PRIMARY KEY (I_COD_SITUACAO);
ALTER TABLE TAREFAS ADD CONSTRAINT PK_TAREFAS PRIMARY KEY (I_COD_TAREFA);
ALTER TABLE TIPO ADD CONSTRAINT PK_TIPO PRIMARY KEY (I_COD_TIPO);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (I_COD_USUARIO);
ALTER TABLE VERSAO ADD CONSTRAINT PK_VERSAO PRIMARY KEY (I_COD_VERSAO);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ANOTACAO ADD CONSTRAINT FK_ANOTACAO_1 FOREIGN KEY (I_COD_TAREFA) REFERENCES TAREFAS (I_COD_TAREFA);
ALTER TABLE ANOTACAO ADD CONSTRAINT FK_ANOTACAO_2 FOREIGN KEY (I_COD_USUARIO) REFERENCES USUARIOS (I_COD_USUARIO);
ALTER TABLE DOCUMENTOS ADD CONSTRAINT FK_DOCUMENTOS_1 FOREIGN KEY (I_COD_TAREFA) REFERENCES DOCUMENTOS (I_COD_DOCUMENTO);
ALTER TABLE EVENTO ADD CONSTRAINT FK_EVENTO_1 FOREIGN KEY (I_COD_TAREFA) REFERENCES TAREFAS (I_COD_TAREFA);
ALTER TABLE EVENTO ADD CONSTRAINT FK_EVENTO_2 FOREIGN KEY (I_COD_TIPO) REFERENCES TIPO (I_COD_TIPO);
ALTER TABLE TAREFAS ADD CONSTRAINT FK_TAREFAS_1 FOREIGN KEY (I_COD_VERSAO) REFERENCES VERSAO (I_COD_VERSAO);
ALTER TABLE TAREFAS ADD CONSTRAINT FK_TAREFAS_2 FOREIGN KEY (I_COD_SITUACAO) REFERENCES SITUACAO (I_COD_SITUACAO);
ALTER TABLE TAREFAS ADD CONSTRAINT FK_TAREFAS_3 FOREIGN KEY (I_COD_PRIORIDADE) REFERENCES PRIORIDADES (I_COD_PRIORIDADE);

/******************************************************************************/
/***                              Sequences                                 ***/
/******************************************************************************/

CREATE SEQUENCE seq_evento
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_situacao
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_tarefas
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_tipo
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_usuarios
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_versao
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_prioridade
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_documentos
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_anotacao
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
  
CREATE SEQUENCE seq_r_usuarios
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 1;
